apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "quartz.fullname" . }}
  labels:
    {{- include "quartz.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "quartz.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "quartz.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: quartz
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
