apiVersion: v1
kind: Service
metadata:
  name: {{ include "quartz.fullname" . }}
  labels:
    {{- include "quartz.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "quartz.selectorLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
