# Default values for quartz.
# This is a YAML-formatted file.

replicaCount: 2

image:
  repository: registry.digitalocean.com/oro-registry/oro-brand
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: nginx
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-digitalocean
  hosts:
    - host: brand.oro.ad
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: quartz-tls
      hosts:
        - brand.oro.ad
